// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web1.Context;

namespace Web1.Migrations
{
    [DbContext(typeof(KindContext))]
    [Migration("20221211233138_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("Web1.Model.Album", b =>
                {
                    b.Property<string>("AlbumTitle")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumDescription")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AlbumTitle");

                    b.ToTable("Albums");
                });

            modelBuilder.Entity("Web1.Model.Image", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlbumTitle1")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlbumTitle1");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Web1.Model.Image", b =>
                {
                    b.HasOne("Web1.Model.Album", null)
                        .WithMany("Images")
                        .HasForeignKey("AlbumTitle1");
                });

            modelBuilder.Entity("Web1.Model.Album", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
